# The URL the site will be built for
base_url = "https://youngstownactioncenter.com"

#base_url = "https://mitch.youngstownactioncenter-site.pages.dev/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Disabled for obvious reasons.
# Add the below code back in to the index template if ever needed.
# {% set page = get_page(path=config.extra.featured_newsletter) %}
# <div class="panel">
#     <div class="panel-header-group">
#         <h2><i>Featured Newsletter</i></h2>
#         <h2>
#             <a href="{{ page.path }}" class="downstyle-anchor">{{ page.title }}</a>
#         </h2>
#         {{ page.date }}
#     </div>
#     <div class="panel-content">
#     {{ page.content | safe }}
#     </div>
# </div>

# featured_newsletter = "newsletter/1/index.md"

[[extra.nav]]
title = "Home"
link = ""

[[extra.nav]]
title = "About"
[[extra.nav.dropdown]]
title = "The YAC"
link = "@/the_yac.md"
[[extra.nav.dropdown]]
title = "Our Mission"
link = "@/our_mission.md"

[[extra.nav]]
title = "Partners & Projects"
[[extra.nav.dropdown]]
title = "Org Directory"
link = "@/org_directory.md"
[[extra.nav.dropdown]]
title = "Community Greeters"
link = "@/greeters.md"
[[extra.nav.dropdown]]
title = "MV Solidarity Library"
link = "@/movement_library.md"
[[extra.nav.dropdown]]
title = "The Guillo-Zine Project"
link = "@/zine_library.md"
[[extra.nav.dropdown]]
title = "NARCAN Distribution"
link = "@/get_narcan.md"
[[extra.nav.dropdown]]
title = "Community Garden"
link = "@/garden.md"

[[extra.nav]]
title = "Events"
[[extra.nav.dropdown]]
title = "Calendar"
link = "@/calendar.md"
[[extra.nav.dropdown]]
title = "Featured Events"
link = "@/events.md"

[[extra.nav]]
title = "Get Involved"
link = "@/get_involved.md"

[[extra.nav]]
title = "Donate"
[[extra.nav.dropdown]]
title = "OpenCollective"
external_link = "https://opencollective.com/youngstown-action-center"
[[extra.nav.dropdown]]
title = "Amazon Wishlist"
external_link = "https://www.amazon.com/hz/wishlist/ls/3V4BV6JF6ZXKI?ref=wl_share"

[[extra.nav]]
title = "Contact Us"
link = "@/contact.md"

